package com.are.recovery.exec;

import com.are.recovery.config.RecoveryMatrixProperties;
import com.are.recovery.event.RecoveryEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

import java.util.Optional;

import com.are.recovery.audit.AuditLogger;

@Component
public class RecoveryActionExecutor {

    private static final Logger log = LoggerFactory.getLogger(RecoveryActionExecutor.class);
    private final RecoveryMatrixProperties matrixProperties;
    private final CooldownRegistry cooldownRegistry;
    private final ActionInvoker actionInvoker;
    private final AuditLogger auditLogger;

    public RecoveryActionExecutor(RecoveryMatrixProperties matrixProperties,
                                  CooldownRegistry cooldownRegistry,
                                  ActionInvoker actionInvoker,
                                  AuditLogger auditLogger) {
        this.matrixProperties = matrixProperties;
        this.cooldownRegistry = cooldownRegistry;
        this.actionInvoker = actionInvoker;
        this.auditLogger = auditLogger;
    }

    @EventListener
    public void handleRecoveryEvent(RecoveryEvent event) {
        log.info("Evaluating RecoveryEvent for service: {}, alert: {}, correlationId: {}",
                event.getServiceName(), event.getAlertName(), event.getCorrelationId());

        if (!cooldownRegistry.canExecute(event.getServiceName())) {
            log.warn("Service {} is in COOLDOWN. Ignoring alert {}.", event.getServiceName(), event.getAlertName());
            return;
        }

        Optional<RecoveryMatrixProperties.RecoveryRule> matchedRule = matrixProperties.getMatrix().stream()
                .filter(rule -> matches(rule, event.getAlertName()))
                .findFirst();

        if (matchedRule.isPresent()) {
            RecoveryMatrixProperties.RecoveryRule rule = matchedRule.get();
            log.info("Matched rule [{}] for alert [{}]. Primary Action: {}",
                    rule.getFault(), event.getAlertName(), rule.getPrimaryAction());

            boolean success = actionInvoker.invoke(rule.getPrimaryAction(), event.getServiceName());
            if (success) {
                cooldownRegistry.recordExecution(event.getServiceName());
                auditLogger.logAction(event.getCorrelationId(), event.getServiceName(), rule.getPrimaryAction(), "SUCCESS");
                log.info("Successfully executed {} on {}.", rule.getPrimaryAction(), event.getServiceName());
            } else {
                auditLogger.logAction(event.getCorrelationId(), event.getServiceName(), rule.getPrimaryAction(), "FAILED");
                log.error("Failed to execute {}. Secondary action might be required.", rule.getPrimaryAction());
                if (rule.getSecondaryAction() != null) {
                     boolean secSuccess = actionInvoker.invoke(rule.getSecondaryAction(), event.getServiceName());
                     cooldownRegistry.recordExecution(event.getServiceName());
                     auditLogger.logAction(event.getCorrelationId(), event.getServiceName(), rule.getSecondaryAction(), secSuccess ? "SUCCESS" : "FAILED");
                }
            }
        } else {
            log.warn("No recovery rule mapped for alert: {}", event.getAlertName());
        }
    }

    private boolean matches(RecoveryMatrixProperties.RecoveryRule rule, String alertName) {
        // Map alert names generated by Prometheus/Loki to matrix configuration
        if ("ServiceDown".equalsIgnoreCase(alertName) && "Service Crash".equalsIgnoreCase(rule.getFault())) {
            return true;
        }
        if ("HighErrorRate".equalsIgnoreCase(alertName) && "High Error Rate".equalsIgnoreCase(rule.getFault())) {
            return true;
        }
        if ("HighLatency".equalsIgnoreCase(alertName) && "Response Time Degradation".equalsIgnoreCase(rule.getFault())) {
            return true;
        }
        if ("DbConnectionTimeout".equalsIgnoreCase(alertName) && "Connection Pool Exhaustion".equalsIgnoreCase(rule.getFault())) {
            return true;
        }
        if ("HighMemoryUsage".equalsIgnoreCase(alertName) && "Memory Leak".equalsIgnoreCase(rule.getFault())) {
            return true;
        }
        return false;
    }
}
