-- liquibase formatted sql

-- changeset solomon:1775754043088-1
CREATE TABLE accounts (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted BOOLEAN NOT NULL, "deletedAt" TIMESTAMP(6) WITHOUT TIME ZONE, "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, "accountName" VARCHAR(100) NOT NULL, "accountNumber" VARCHAR(20) NOT NULL, balance numeric(19, 4) NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(20) NOT NULL, version BIGINT, user_id BIGINT NOT NULL, CONSTRAINT "accountsPK" PRIMARY KEY (id));
-- rollback DROP TABLE accounts;

-- changeset solomon:1775754043088-2
CREATE TABLE otps (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted BOOLEAN NOT NULL, "deletedAt" TIMESTAMP(6) WITHOUT TIME ZONE, "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, "expiresAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, otp VARCHAR(255) NOT NULL, "usedAt" TIMESTAMP(6) WITHOUT TIME ZONE, user_id BIGINT NOT NULL, CONSTRAINT "otpsPK" PRIMARY KEY (id));
-- rollback DROP TABLE otps;

-- changeset solomon:1775754043088-3
CREATE TABLE payments (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount numeric(19, 4) NOT NULL, "correlationId" VARCHAR(50), "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, currency VARCHAR(3) NOT NULL, description VARCHAR(500), "failureReason" VARCHAR(500), "fromAccountId" BIGINT NOT NULL, reference VARCHAR(100), status VARCHAR(20) NOT NULL, "toAccountId" BIGINT NOT NULL, "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT "paymentsPK" PRIMARY KEY (id));
-- rollback DROP TABLE payments;

-- changeset solomon:1775754043088-4
CREATE TABLE transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted BOOLEAN NOT NULL, "deletedAt" TIMESTAMP(6) WITHOUT TIME ZONE, "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, "accountId" BIGINT NOT NULL, amount numeric(19, 4) NOT NULL, "balanceAfter" numeric(19, 4), "balanceBefore" numeric(19, 4), "correlationId" VARCHAR(50) NOT NULL, description VARCHAR(500), reference VARCHAR(100) NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, account_id BIGINT NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "transactionsPK" PRIMARY KEY (id));
-- rollback DROP TABLE transactions;

-- changeset solomon:1775754043088-5
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted BOOLEAN NOT NULL, "deletedAt" TIMESTAMP(6) WITHOUT TIME ZONE, "updatedAt" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, email VARCHAR(255) NOT NULL, "firstName" VARCHAR(255) NOT NULL, "lastName" VARCHAR(255) NOT NULL, "phoneNumber" VARCHAR(20), type VARCHAR(255) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));
-- rollback DROP TABLE users;

-- changeset solomon:1775754043088-6
ALTER TABLE accounts ADD CONSTRAINT UC_ACCOUNTSACCOUNTNUMBER_COL UNIQUE ("accountNumber");
-- rollback ALTER TABLE accounts DROP CONSTRAINT UC_ACCOUNTSACCOUNTNUMBER_COL;

-- changeset solomon:1775754043088-7
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);
-- rollback ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

-- changeset solomon:1775754043088-8
ALTER TABLE transactions ADD CONSTRAINT "FK20w7wsg13u9srbq3bd7chfxdh" FOREIGN KEY (account_id) REFERENCES accounts (id);
-- rollback ALTER TABLE transactions DROP CONSTRAINT "FK20w7wsg13u9srbq3bd7chfxdh";

-- changeset solomon:1775754043088-9
ALTER TABLE accounts ADD CONSTRAINT "FKnjuop33mo69pd79ctplkck40n" FOREIGN KEY (user_id) REFERENCES users (id);
-- rollback ALTER TABLE accounts DROP CONSTRAINT "FKnjuop33mo69pd79ctplkck40n";

-- changeset solomon:1775754043088-10
ALTER TABLE transactions ADD CONSTRAINT "FKqwv7rmvc8va8rep7piikrojds" FOREIGN KEY (user_id) REFERENCES users (id);
-- rollback ALTER TABLE transactions DROP CONSTRAINT "FKqwv7rmvc8va8rep7piikrojds";

-- changeset solomon:1775754043088-11
ALTER TABLE otps ADD CONSTRAINT "FKseso6nlp9f5fbuilrngn3pbyi" FOREIGN KEY (user_id) REFERENCES users (id);
-- rollback ALTER TABLE otps DROP CONSTRAINT "FKseso6nlp9f5fbuilrngn3pbyi";

