services:
  account-uri: http://account-service:8082
  payment-uri: http://payment-service:8081
  notification-uri: http://notification-worker:8085

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/are_db
  rabbitmq:
    host: rabbitmq
