server:
    port: 8085

spring:
    application:
        name: notification-worker
    threads:
        virtual:
            enabled: true
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

management:
    endpoints:
        web:
            exposure:
                include: health,prometheus,info,env,shutdown
    endpoint:
        health:
            show-details: always
        shutdown:
            access: UNRESTRICTED
    metrics:
        tags:
            application: notification-worker

springdoc:
    swagger-ui:
        url: /v3/api-docs
    info:
        title: Notification Worker API
        version: 1.0.0
        description: API for notification services.
