server:
    port: 8085
    forward-headers-strategy: framework

spring:
    application:
        name: notification-worker
    # boot:
    #     admin:
    #         client:
    #             url: http://localhost:8086
    threads:
        virtual:
            enabled: true
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME:solomonabu90@gmail.com}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${MAIL_SMTP_AUTH:true}
                    starttls:
                        enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
                    
management:
    endpoints:
        web:
            exposure:
                include: health,prometheus,info,env,shutdown
    endpoint:
        health:
            show-details: always
        shutdown:
            access: UNRESTRICTED
    metrics:
        tags:
            application: notification-worker
